### ISSUE TITLE
10.* is a LAN IP in some places

### ISSUE THREAD

**Issue by ioistired** [cryptostorm/cstorm_deepDNS#1]
Where I am right now, deepDNS doesn't work because `10.99.100.203` for example is an actual IP on my LAN.

Meaning deepDNS doesn't work here, because my device tries to connect to a random local machine instead of a hidden service.

**Comment by df-cryptostorm** [comment]
The transparent .onion access part of DeepDNS does use:
VirtualAddrNetworkIPv4 10.99.0.0/16
in the tor config. 

Unfortunately, the only way to change this would be to do so for every server, and there's always a risk of whatever it's changed to conflicting with someone else's network configuration.

The best solution would be for you to use Tor directly instead of the transparent access DeepDNS provides, or if you're just browsing .onion sites then torstorm.org would suffice
