### ISSUE TITLE
minisign.pub not the same key that is being used to sign the .md files

### ISSUE THREAD

**Issue by paschun** [cryptostorm/cstorm_deepDNS#8]
```
> minisign -Vm cs-relays.md -p minisign.pub

Signature verification failed
```

Also 
```
> minisign -H -Vm cs-relays.md -p minisign.pub -x cs-relays.md.minisig
Legacy (non-prehashed) signature found
```

**Comment by df-cryptostorm** [comment]
Oops. minisign on the server I push the relays/resolvers updates from had a broken libsodium, which broke minisign.
Updated both, all good now.

**Comment by df-cryptostorm** [comment]
One more thing, I tried updating it to the new hashed signature format, but the problem is the dnscrypt-proxy included in our Windows client needs an older dnscrypt-proxy since they dropped win7 support, and some of our customers are still using win7. So instead, I'll be signing using minisign's -l arg to keep the legacy format.
