### ISSUE TITLE
DNSSEC Anonymized DNS

### ISSUE THREAD

**Issue by huv9** [cryptostorm/cstorm_deepDNS#9]
Turn on dnssec on resolvers and relays

**Comment by df-cryptostorm** [comment]
We do support DNSSEC on all the resolvers, but we're not forcing validation of all queries. It's only used if the client requests it, which is why we don't have the DNSSEC bit on in our DNSCrypt stamps.

The upstream is a local PowerDNS recursor, and according to https://doc.powerdns.com/recursor/dnssec.html the default dnssec setting is "process":


"When [dnssec] is set to "process" the behaviour is similar to [process-no-validate]. However, the recursor will try to validate the data if at least one of the DO or AD bits is set in the query; in that case, it will set the AD-bit in the response when the data is validated successfully, or send SERVFAIL when the validation comes up bogus."

We're using PowerDNS 5.0.2 or 5.0.3 on our servers, so they all use this "process" default. Prior to version 4.5.0 the default was "process-no-validate", so we used that in earlier versions.

The highest setting is "validate", which is the "highest mode of DNSSEC processing. In this mode, all responses will be be validated and queries will be answered with a SERVFAIL in case of bogus data, even if the client did not request validation by setting the AD or DO bit." We tried using "validate" in the past, but found that it broke too many legitimate (or poorly configured) popular websites/services, so we decided to keep it at the current default.
